services:
  database:
    image: postgres:latest
    command: postgres -c config_file="/etc/postgresql.conf"
    network_mode: host
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=rinha_backend
    volumes:
      - database:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '2GB'

  api1:
    # image: oliveigah/rinha-backend:finalv2
    build: .
    depends_on:
      - database
    network_mode: host
    environment:
      DOCKER_COMPOSE_MODE: "HOST"
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 3000
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NAME: "api1"
      RELEASE_NODE: "api1@127.0.0.1"
      RELEASE_DISTRIBUTION: "name"
      BOOTSTRAP_NODES: "api2@127.0.0.1"
      DB_CONNS: 120
    healthcheck:
      test: curl -f http://localhost:3000
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.4GB'

  api2:
    # image: oliveigah/rinha-backend:finalv2
    build: .
    depends_on:
      - api1
    network_mode: host
    environment:
      DOCKER_COMPOSE_MODE: "HOST"
      ERL_MAX_PORTS: 2048
      HTTP_SERVER_PORT: 3001
      RELEASE_COOKIE: "secret_cookie"
      RELEASE_NAME: "api2"
      RELEASE_NODE: "api2@127.0.0.1"
      RELEASE_DISTRIBUTION: "name"
      BOOTSTRAP_NODES: "api1@127.0.0.1"
      DB_CONNS: 120
    healthcheck:
      test: curl -f http://localhost:3001
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '0.4GB'

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - ./nginx_host.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: '0.2GB'

volumes:
  database: